### PR TITLE
Add random number & symbol separators

### PR DESCRIPTION
**Pull request by jc00ke**
This adds special `-s` values that will generate random values.

### CODE REVIEW

**Comment by jc00ke** [comment]
I happened to see your [post on Hachyderm](https://hachyderm.io/@schlink/111279779675133501) and thought it would be fun on a Sunday to add random separators. This is my first Rust contribution, so if you have any feedback, I'm all ears!

I first went down the path of adding a new flag like `-r` but I thought it would end up being more changes and kinda weird. I'm not in love with the `_*` format, but thought it was a good place to start.

**Comment by sts10** [comment]
ooo elegant. Thanks so much!

**Comment by sts10** [comment]
One note for ya: This line `Uniform::from(0..9).sample(rng).to_string()` returns 0 through 9 _exclusive_, meaning it will never return `9`, just 0 through 8. 

You could make it _inclusive_ with an `=`: `Uniform::from(0..=9).sample(rng).to_string()`. 

Though I'm going to use [`get_range()`](https://docs.rs/rand/latest/rand/trait.Rng.html#method.gen_range) for now:
```rust
fn get_random_number(rng: &mut impl Rng) -> String {
    rng.gen_range(0..=9).to_string()
}
```

**Comment by jc00ke** [comment]
Oops, I didn't realize it was exclusive, good catch. `gen_range` looks good for this too.

**Pull request merged**
